<?php

/**
 * Implements hook_block_info().
 */
function company_twitter_block_block_info() {
  $blocks = array();
  $blocks['company_twitter_block'] = array(
    'info' => t('Company twitter block'),
  );
  return $blocks;
}

 function company_twitter_block_block_view($delta = '') {
  $block = array();
  
  switch ($delta) {
    case 'company_twitter_block':
      $block['subject'] = t('Company Twitter block');

      $twitter = ('<div> <a class="twitter-timeline" data-theme="dark" href="https://twitter.com/TwitterDev/timelines/539487832448843776?ref_src=twsrc%5Etfw">National Park Tweets - Curated tweets by TwitterDev</a> 
     <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></div>');
     
        $block['content'] = $twitter;
        break;
    }
    return $block;
  }
